homepage:
    path: /
    defaults: { _controller: AppBundle:Default:index }

website_delete:
    path: /delete/{reference}
    defaults: { _controller: AppBundle:Default:websiteDelete }
    options:
        expose: true